version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: flask_api_mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: api_contact
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - flask_network

volumes:
  mysql_data:

networks:
  flask_network: